spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:metaclone_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  host: localhost

kafka:
  bootstrap-servers: ${KAFKA_SERVER}

secret:
  access-token-key: ${SECRET_ACCESS_TOKEN_KEY}
  refresh-token-key: ${SECRET_REFRESH_TOKEN_KEY}
  access-token-ttl: ${SECRET_ACCESS_TOKEN_TTL}
  refresh-token-ttl: ${SECRET_REFRESH_TOKEN_TTL}
  event-auth-topic: ${EVENT_AUTH_TOPIC}
