spring:
  application:
    name: users-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
    redis:
      time-to-live: ${USERS_CACHE_TTL}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
  host: localhost

kafka:
  bootstrap-servers: localhost:9092
  topic:
    user-events: auth.user.created
    avatar-update: avatar.update
  group-id:
    users-service: users-service

secret:
  access-token-key: ${ACCESS_TOKEN_KEN}

logging:
  level:
    org.springframework.security: DEBUG